"""empty message

Revision ID: 2c052fce49bf
Revises: 
Create Date: 2020-08-04 16:36:49.636631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c052fce49bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cows_breeds1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('longtitude1', sa.Float(), nullable=False),
    sa.Column('latitude1', sa.Float(), nullable=False),
    sa.Column('breed1', sa.String(), nullable=False),
    sa.Column('type1', sa.String(), nullable=False),
    sa.Column('udoy1', sa.Float(), nullable=False),
    sa.Column('jir1', sa.Float(), nullable=False),
    sa.Column('belok1', sa.Float(), nullable=False),
    sa.Column('massa1', sa.Float(), nullable=False),
    sa.Column('perviy_otel_dney1', sa.Float(), nullable=False),
    sa.Column('v_otelah1', sa.Float(), nullable=False),
    sa.Column('vibitiya_v_otelah1', sa.Float(), nullable=False),
    sa.Column('servis_period1', sa.Float(), nullable=False),
    sa.Column('suhostoyniy_period1', sa.Float(), nullable=False),
    sa.Column('vihod_telyat_na100_golov1', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cows_breeds2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('longtitude2', sa.Float(), nullable=False),
    sa.Column('latitude2', sa.Float(), nullable=False),
    sa.Column('breed2', sa.String(), nullable=False),
    sa.Column('type2', sa.String(), nullable=False),
    sa.Column('udoy2', sa.Float(), nullable=False),
    sa.Column('jir2', sa.Float(), nullable=False),
    sa.Column('belok2', sa.Float(), nullable=False),
    sa.Column('massa2', sa.Float(), nullable=False),
    sa.Column('perviy_otel_dney2', sa.Float(), nullable=False),
    sa.Column('v_otelah2', sa.Float(), nullable=False),
    sa.Column('vibitiya_v_otelah2', sa.Float(), nullable=False),
    sa.Column('servis_period2', sa.Float(), nullable=False),
    sa.Column('suhostoyniy_period2', sa.Float(), nullable=False),
    sa.Column('vihod_telyat_na100_golov2', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cows_breeds2')
    op.drop_table('cows_breeds1')
    # ### end Alembic commands ###
