"""empty message

Revision ID: 7cf9963ea300
Revises: 
Create Date: 2020-08-31 16:28:15.982609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cf9963ea300'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cows_breeds1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('longtitude1', sa.Float(), nullable=False),
    sa.Column('latitude1', sa.Float(), nullable=False),
    sa.Column('breed1', sa.String(), nullable=False),
    sa.Column('type1', sa.String(), nullable=False),
    sa.Column('yeild1', sa.Float(), nullable=False),
    sa.Column('fat1', sa.Float(), nullable=False),
    sa.Column('protein1', sa.Float(), nullable=False),
    sa.Column('weight1', sa.Float(), nullable=False),
    sa.Column('first_calving_days1', sa.Float(), nullable=False),
    sa.Column('age_in_calving1', sa.Float(), nullable=False),
    sa.Column('leaving_in_calving1', sa.Float(), nullable=False),
    sa.Column('service_period1', sa.Float(), nullable=False),
    sa.Column('dry_period1', sa.Float(), nullable=False),
    sa.Column('calving_per100_heads1', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cows_breeds2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('longtitude2', sa.Float(), nullable=False),
    sa.Column('latitude2', sa.Float(), nullable=False),
    sa.Column('breed2', sa.String(), nullable=False),
    sa.Column('type2', sa.String(), nullable=False),
    sa.Column('udoy2', sa.Float(), nullable=False),
    sa.Column('jir2', sa.Float(), nullable=False),
    sa.Column('belok2', sa.Float(), nullable=False),
    sa.Column('massa2', sa.Float(), nullable=False),
    sa.Column('perviy_otel_dney2', sa.Float(), nullable=False),
    sa.Column('v_otelah2', sa.Float(), nullable=False),
    sa.Column('vibitiya_v_otelah2', sa.Float(), nullable=False),
    sa.Column('servis_period2', sa.Float(), nullable=False),
    sa.Column('suhostoyniy_period2', sa.Float(), nullable=False),
    sa.Column('vihod_telyat_na100_golov2', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cows_breeds2')
    op.drop_table('cows_breeds1')
    # ### end Alembic commands ###
